Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import cvxpy as cp

# Define the optimization variables
x = cp.Variable(2)

# Define the objective function
objective = cp.Minimize(cp.sum_squares(x))

# Define the constraint
constraint = [x[0] + x[1] >= 1]

# Create the optimization problem
problem = cp.Problem(objective, constraint)

# Solve the problem using the Mosek solver
problem.solve(solver=cp.MOSEK)

# Print the optimal solution and optimal value
print("Optimal solution: x1 = {}, x2 = {}".format(np.round(x[0].value,3), np.round(x[1].value,3)))
print("Optimal value: {}".format(np.round(problem.value,3)))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 19[0m
[1;32m     16[0m problem[38;5;241m.[39msolve(solver[38;5;241m=[39mcp[38;5;241m.[39mMOSEK)
[1;32m     18[0m [38;5;66;03m# Print the optimal solution and optimal value[39;00m
[0;32m---> 19[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mOptimal solution: x1 = [39m[38;5;132;01m{}[39;00m[38;5;124m, x2 = [39m[38;5;132;01m{}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat([43mnp[49m[38;5;241m.[39mround(x[[38;5;241m0[39m][38;5;241m.[39mvalue,[38;5;241m3[39m), np[38;5;241m.[39mround(x[[38;5;241m1[39m][38;5;241m.[39mvalue,[38;5;241m3[39m)))
[1;32m     20[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mOptimal value: [39m[38;5;132;01m{}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(np[38;5;241m.[39mround(problem[38;5;241m.[39mvalue,[38;5;241m3[39m)))

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

