Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

w = np.linspace(0,1,100)
sr = (0.3*20*w+0.2*10*(1-w))/np.sqrt(9*w**2+16*(1-w)**2)

print( w[np.argmax(sr)], np.max(sr) )
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      4[0m w [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m,[38;5;241m1[39m,[38;5;241m100[39m)
[1;32m      5[0m sr [38;5;241m=[39m ([38;5;241m0.3[39m[38;5;241m*[39m[38;5;241m20[39m[38;5;241m*[39mw[38;5;241m+[39m[38;5;241m0.2[39m[38;5;241m*[39m[38;5;241m10[39m[38;5;241m*[39m([38;5;241m1[39m[38;5;241m-[39mw))[38;5;241m/[39mnp[38;5;241m.[39msqrt([38;5;241m9[39m[38;5;241m*[39mw[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m[38;5;241m+[39m[38;5;241m16[39m[38;5;241m*[39m([38;5;241m1[39m[38;5;241m-[39mw)[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m)

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

